apiVersion: v1

kind: Pod

metadata:
  name: liveness-pod

spec:
  containers:
  - name: liveness
    image: nginx:1.22.0

    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
