apiVersion: v1
  
kind: Pod
  
metadata:
  name: pod-with-secret-env
  labels:
    app: pod-with-secret-env
  
spec:
  containers:
  - name: nginx 
    image: nginx
  
    envFrom:
    - secretRef:
        name: mysecret
