apiVersion: v1

kind: Pod

metadata: 
  name: pod-with-configmap
  labels:
    app: pod-with-configmap

spec: 
  containers:
    - name: nginx
      image: nginx
 
      envFrom:
      - configMapRef:
          name: myconfigmap
