apiVersion: v1
kind: Service
metadata:
  name: wp-service
  labels:
    app: wordpress
  namespace: wordpress
spec:
  ports:
  - name: wp-service
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
    