apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        - name: MYSQL_USER 
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: MYSQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        ports:
          - containerPort: 3306
            protocol: TCP
        resources:
          limits:
            cpu: "250m"
            memory: "1Gi"
      volumes:  
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-mysql