apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: demo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data