apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: clear-nginx-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: clear-nginx
  type: NodePort