apiVersion: v1
metadata:
  name: my-secret
  namespace: wordpress
  labels:
    app: mysql
    tier: database    
data:
  password: a2hlbWFpcw== 
  user: a2hlbWFpcw==
  database: a2hlbWFpcw== 
kind: Secret

type: Opaque