apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: pv-mysql
  labels:
    type: local
    app: pv-mysql
    tier: database
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-mysql"