apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: pvc-mysql
  labels:
    app: pvc-mysql
    tier: database
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-mysql   