apiVersion: v1
kind: Service
metadata:
  #labels:
   # app: mysql-service
    #tier: database
  name: mysql-service
  namespace: wordpress
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysqll
    #tier: database
  type: ClusterIP